test: &default
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID:     AZdjEFNocVND5dsRXYgKn0d_zHOHZ9EBp5N9UNgMjjCBwNIOwKVZ3zjblwGSdHi7e0x-0-uYdRSdKozy
  PAYPAL_CLIENT_SECRET:   EMjfItenVB0BIHZS0pfo2CLJme2EvIp26KuEx2d2OwSxQOCOA-DRi-fWT4V6N4PPlzVFkipdwBPr7--t
  STRIPE_PUBLISHABLE_KEY: pk_test_yVdciim2vQKihKem2AuaWcRP00KX2grs4F
  STRIPE_SECRET_KEY: sk_test_9CIeIcXrELSe4EI8UsWdNmIu00EDNF1z5m
development:
  <<: *default